version: '3.6'
services:
  keycloak-auth:
    image: quay.io/keycloak/keycloak:23.0.4
    ports:
      - "8181:8181"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
      - --http-port=8181
    volumes:
      - E:/spring-boot/spring-boot-microservices/realms/realm-export.json:/opt/keycloak/data/import/realm.json

