version: '3.1'
services:
  zipkin:
    image: openzipkin/zipkin:2
    ports:
      - '9411:9411'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9411 || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

